### ISSUE TITLE
Evalution when label imbalance

### ISSUE THREAD

**Issue by yuntaod** [rotot0/tab-ddpm#28]
Hi,

I want to know how you deal with imbalance label problem? When the label distribution is highly skewed, the generative model may only generate one class label, which cannot use to evaluate ROC AUC, even with cross validation. Besides, should I use cross validation  for real data? I cannot find the codes to tackle this problem, looking forward to your reply! Thanks!

**Comment by rotot0** [comment]
Hi,

Sorry for the late response. We did not deal with the imbalance problem in a specific way, since on our datasets model worked good enough even with label imbalance. But probably you could try loss re-weighting, or sample minority class more often (than sampling according to empirical distribution).
