### ISSUE TITLE
Default hyperparameters for TabDDPM

### ISSUE THREAD

**Issue by yuntaod** [rotot0/tab-ddpm#29]
Hi,

I found TabDDPM needs to tune the hyerparameters for each dataset (even each ML evaluators). I want to know if there are any recommended parameters that can performe good on every dataset? Or TabDDPM is sensitive to the hyperparameters?

Looking forward to your reply!
Best,

**Comment by rotot0** [comment]
Hi, it really depends on the dataset (both sensitivity to hyperparameters and the "best" set of them), but I think on the most datasets even small MLP should be good enough. Take 'exp/abalone/ddpm_cb_best' as a starting point. As for ML evaluators (CatBoost), I think it is important that you are sure that it performs well (since it is the main evaluation metric), thus I would not recommend to just use some default hyperparamters.

Thanks for your question!
